server:
  port: 8888

app:
  api-prefix: "/api/v1"

identity:
    url: "http://localhost:8080/identity"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: myInstanceCircuitBreaker
                fallbackUri: forward:/fallback/identity-service
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/user-profile/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: myInstanceCircuitBreaker
                fallbackUri: forward:/fallback/profile-service
        - id: notification_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: myInstanceCircuitBreaker
                fallbackUri: forward:/fallback/notification-service
        - id: post_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: myInstanceCircuitBreaker
                fallbackUri: forward:/fallback/post-service


resilience4j.circuitbreaker:
  instances:
    myInstanceCircuitBreaker:
      registerHealthIndicator: true
      sliding-window-type: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5
      automatic-transition-from-open-to-half-open-enabled: true
resilience4j:
  timelimiter:
    configs:
        default:
            timeout-duration: 3s
  retry:
    configs:
        default:
            max-attempts: 3
            waitDuration: 2s

