server:
  port: 8086
  servlet:
    context-path: /search

kafka-topic:
  add-profile-elastic: "add-profile-elastic"

spring:
  application:
    name: search-service
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/