server:
  port: 8081
  servlet:
    context-path: /profile

avatar:
  default: "http://localhost:8888/api/v1/file-service/file/upload/avatar/default.jpg"

kafka-topic:
  profile-avatar-update: "profile-avatar-update"
  add-profile-elastic: "add-profile-elastic"

spring:
  neo4j:
    authentication:
      username: "neo4j"
      password: "neo4j_password"
      uri: "bolt://localhost:7687"
  driver:
    config:
      encrypted: true
  application:
    name: profile-service

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/