server:
  port: 8081
  servlet:
    context-path: /profile

spring:
    neo4j:
      authentication:
        username: "neo4j"
        password: "neo4j_password"
        uri: "bolt://localhost:7687"
    driver:
      config:
        encrypted: true