server:
  port: 8889

app:
  prefix: /api/v1
  services:
    post:
      name: "post-service"
    profile:
      name: "profile-service"

services:
  post:
    url: "http://localhost:8888/${app.prefix}/${app.services.post.name}/post"
  profile:
    url: "http://localhost:8888/${app.prefix}/${app.services.profile.name}/profile"

spring:
  application:
    name: aggregator-service
  webflux:
    base-path: /aggregator

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

